sudo: required
services:
  - docker

before_install: 
  - docker build -t yvalain/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true yvalain/react-test npm test

after_success:
  - docker build -t yvalain/multi-client ./client
  - docker build -t yvalain/multi-nginx ./nginx
  - docker build -t yvalain/multi-server ./server
  - docker build -t yvalain/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yvalain/multi-client
  - docker push yvalain/multi-nginx
  - docker push yvalain/multi-server
  - docker push yvalain/multi-worker
  